name: "Run Docs CD with UV"

on:
  workflow_dispatch:

jobs:
  build-deploy-docs:
    if: github.repository == 'zilliztech/deep-searcher'
    uses: ./.github/workflows/docs.yml
    with:
      deploy: true
    permissions:
      contents: write
