name: "Run Docs CI with UV"

on:
  workflow_dispatch:
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

jobs:
  build-docs:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.head.repo.full_name != 'zilliztech/deep-searcher') }}
    uses: ./.github/workflows/docs.yml
    with:
      deploy: false
